import { isValueEqual } from './value-equal'
export default isValueEqual
export {
  isValueEqual
}
export * from './array'
export * from './array-like'
export * from './binary-match'
export * from './boolean'
export * from './decimal'
export * from './defined'
export * from './empty-array'
export * from './equal'
export * from './false'
export * from './falsey'
export * from './finite'
export * from './function'
export * from './greater-than'
export * from './greater-than-equal-to'
export * from './http'
export * from './infinite'
export * from './integer'
export * from './iterable'
export * from './key'
export * from './less-than'
export * from './less-than-equal-to'
export * from './nan'
export * from './nil'
export * from './null'
export * from './number'
export * from './object'
export * from './instance'
export * from './promise'
export * from './reg-exp'
export * from './string'
export * from './symbol'
export * from './thennable'
export * from './true'
export * from './truthy'
export * from './undefined'
export * from './valid-integer'
export * from './value'
export * from './window'
export * from './zero'
